import { createRequestHandler, type ServerBuild } from "@remix-run/cloudflare";
import { checkQuotaThrottle, throttleResponse } from "./app/lib/throttle.server";
import { dispatchScheduled } from "./app/lib/cron-router.server";
// build/server/index.js is generated by \`pnpm build\`. Wrangler bundles
// this entry at deploy time, so the import resolves then. Suppressed
// because tsc/IDE may not see the file before the first build.
// @ts-ignore -- generated at build time
import * as serverBuild from "./build/server";

const handleRequest = createRequestHandler(
  serverBuild as unknown as ServerBuild,
  process.env.NODE_ENV,
);

export default {
  async fetch(request: Request, env: unknown, ctx: ExecutionContext) {
    const context = {
      cloudflare: {
        env,
        ctx,
        cf: request.cf,
        caches,
      } as never,
    };
    const { throttle } = await checkQuotaThrottle(context as never);
    if (throttle) return throttleResponse();
    return handleRequest(request, context);
  },
  async scheduled(
    event: { cron: string; scheduledTime: number },
    env: unknown,
    ctx: ExecutionContext,
  ) {
    const context = {
      cloudflare: { env, ctx, caches } as never,
    };
    await dispatchScheduled(event, context);
  },
};
